// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_P4.DbModels;

#nullable disable

namespace Project_P4.Migrations
{
    [DbContext(typeof(Projekt01_HermaContext))]
    [Migration("20220829103140_MIgration1")]
    partial class MIgration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project_P4.DbModels.Expence", b =>
                {
                    b.Property<int>("ExpenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenceId"), 1L, 1);

                    b.Property<decimal>("ExpenceCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("ExpenceDate")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.HasKey("ExpenceId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberId");

                    b.ToTable("Expence", (string)null);
                });

            modelBuilder.Entity("Project_P4.DbModels.ExpGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GroupId")
                        .HasName("PK__ExpGroup__149AF30A2E244628");

                    b.HasIndex(new[] { "GroupName" }, "UQ__ExpGroup__6EFCD434E207C59C")
                        .IsUnique()
                        .HasFilter("[GroupName] IS NOT NULL");

                    b.ToTable("ExpGroup", (string)null);
                });

            modelBuilder.Entity("Project_P4.DbModels.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IncomeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"), 1L, 1);

                    b.Property<decimal>("IncomeCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("IncomeDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.HasKey("IncomeId");

                    b.HasIndex("MemberId");

                    b.ToTable("Income", (string)null);
                });

            modelBuilder.Entity("Project_P4.DbModels.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<decimal?>("MemberBudget")
                        .HasColumnType("money");

                    b.Property<string>("MemberName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MemberId");

                    b.HasIndex(new[] { "MemberName" }, "UQ__Member__BE50FDEF485273A9")
                        .IsUnique()
                        .HasFilter("[MemberName] IS NOT NULL");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Project_P4.DbModels.Expence", b =>
                {
                    b.HasOne("Project_P4.DbModels.ExpGroup", "Group")
                        .WithMany("Expences")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("ref2");

                    b.HasOne("Project_P4.DbModels.Member", "Member")
                        .WithMany("Expences")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("ref3");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Project_P4.DbModels.Income", b =>
                {
                    b.HasOne("Project_P4.DbModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("ref1");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Project_P4.DbModels.ExpGroup", b =>
                {
                    b.Navigation("Expences");
                });

            modelBuilder.Entity("Project_P4.DbModels.Member", b =>
                {
                    b.Navigation("Expences");
                });
#pragma warning restore 612, 618
        }
    }
}
